config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create]
  end
  #resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, :cocktail, presence: true, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :cocktail_set, only: :show
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      redirect_to new_cocktail_path
    end
  end

  private

  def cocktail_set
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktails_path
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(params[:cocktail_id])
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<h2 id='top'>Best Cocktails for our special guest</h2>

<div class="dropdown">
  <button onclick="myFunction()" class="dropbtn">Dropdown</button>
  <div id="myDropdown" class="dropdown-content">
    <% @cocktails.each do |cocktail|  %>
      <a href="<%= "##{cocktail.name.delete(' ')}" %>"><%= cocktail.name %></a>
    <% end  %>
  </div>
  <hr>
</div>

<div class='card-body'>
  <p style='color:black'>You can see the best known cocktails below and see the details of the cocktail by clicking on a cocktail.</p>
  <p style='color:black'>Enjoy the ride!</p>
</div>

<div class='container'>
<% @cocktails.each do |cocktail|  %>
  <div class='card' id='cockt_card'>
    <p class='cockt_name' id="<%= cocktail.name.delete(' ') %>"><%=link_to "#{cocktail.name}", cocktail_path(cocktail)%></p>
    <%= cl_image_tag cocktail.photo.key, height: 200, width: 300, crop: :fill,id:'cock_img' %>
    <br>
  </div>
<% end %>
  <div>
    <p><%= link_to 'Create a new cocktail', new_cocktail_path, class:'btn btn-primary' %></p>
  </div>
</div>
<br>

<div id='top_link'>
  <a href='#header_id' class='btn btn-secondary'>Top</a>
</div>

<script>
  function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
  }

  window.onclick = function(event) {
    if (!event.target.matches('.dropbtn')) {
      let dropdowns = document.getElementsByClassName("dropdown-content");
      let i;
      for (i = 0; i < dropdowns.length; i++) {
        let openDropdown = dropdowns[i];
        if (openDropdown.classList.contains('show')) {
          openDropdown.classList.remove('show');
        }
      }
    }
  }
</script>

app/views/cocktails/new.html.erb
<h2>Create you own cocktail!</h2>

<div class='container'>
  <div class='card' id='round_pic'>
    <%= image_tag ('https://res.cloudinary.com/ds2odybte/image/upload/v1605700829/cocktails_pic_round_lxrmfr.jpg') %>
  </div>
</div>

<div class='container'>
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class:'btn btn-primary' %>
  <% end  %>
</div>

<div style='text-align:center; margin-top: 25px; margin-bottom:25px;'>
  <%= link_to 'Return to Main Page', cocktails_path%>
</div>

app/views/cocktails/show.html.erb
<div class='container'>
  <div class='card' id='cockt_card'>
    <p class='cockt_name'><%= "#{@cocktail.name}" %></p>
    <h4 style="font-family:'Arial Black'; text-shadow: 1px 1px 2px gray; color:#FFFACD; ">Ingredients:</h4>
    <table>
      <tbody>
        <% @cocktail.doses.each do |dose|  %>
        <tr>
          <td><strong><%= "#{dose.description}:" %></strong></td>
          <td style='text-align: center'><%= dose.ingredient.name.capitalize %></td>
          <td>
            <%= link_to cocktail_dose_path(@cocktail,dose), method: :delete, data: { confirm: "Are you sure?" } do %>
              <i class="fa fa-trash destroy_dose"></i>
            <% end  %>
          </td>
        </tr>
        <% end  %>
      </tbody>
    </table>
    <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill, id:'cock_img' %>
    <br>
  </div>

  <div style='display:block; margin-right:auto; margin-left:auto; width:30%;'>
    <h3>Reviews</h3>
    <ul class="list-group">
    <% @cocktail.reviews.each do |review| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span class="badge badge-primary badge-pill">
          <% counter = 0 %>
          <% 5.times do  %>
            <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o'%>"></i>
            <% counter += 1  %>
          <% end  %>
        </span>
      </li>
    <% end %>
    </ul>
    <% @cocktail.reviews.each do |review|  %>
    <p style='font-weight: bold; color:black; font-family: "Arial"'><%= review.content %></p>
    <% end  %>
    <p><em><%= link_to 'New Review', new_cocktail_review_path(@cocktail) %></em></p>
  </div>
  <br>
  <div class='back'><%= link_to 'Create Dose', new_cocktail_dose_path(@cocktail), id:'create_para' %></div>
  <h5 style='text-align:center; margin-top: 25px; margin-bottom:25px;'><%= link_to 'Return to Main Page', cocktails_path %></h5>
</div>

app/views/doses/new.html.erb
<h3>Please create the dose of the ingredient below:</h3>
<div>
  <%= simple_form_for [:cocktail_id, @dose], url: cocktail_doses_path do |f| %>
    <%= f.association :ingredient, input_html: { class: "beautiful-dropdown"}, include_hidden: false %>
    <%= f.input :description %>
    <%= f.button :submit, class:'btn btn-primary' %>
  <% end %>
</div>

<div>
  <p><%= link_to 'Main Page', cocktails_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MrCokctail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <meta name="google-site-verification" content="1VP6UwvmdNM6nPCuij_njyIchfmZ8WkKeRPTueh7r40" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <div class='header' id='header_id'>
      <h1>Mister Cocktail</h1>
      <h3 id='animation'><em>See the best cocktails</em></h3>
    </div>


    <%= yield %>

    <div class='footer'>
      <div>
        <p><em>Created by Can Cimenser</em></p>
      </div>
      <div id='icons'>
        <a href="https://www.facebook.com/can.cimenser" class="fa fa-facebook" target=_blank></a>
        <a href="https://twitter.com/Can_Cimenser" class="fa fa-twitter" target=_blank></a>
        <a href="https://www.instagram.com/cancimenser/" class="fa fa-instagram" target=_blank></a>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reviews/new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [:cocktail_id, @review], url: cocktail_reviews_path(params[:cocktail_id]) do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

<div>
  <p><%= link_to 'Main Page', cocktails_path %></p>
</div>